### ISSUE TITLE
ESPHome external Components

### ISSUE THREAD

**Issue by jesserockz** [DomiStyle/esphome-panasonic-ac#16]
This is great and I hope someday that you decide to get this merged into ESPHome directly. Until then it would be great if you could structure the code as a standard component so that people can use it with [external_components](https://esphome.io/components/external_components.html)

This would allow people to update a lot easier as that is handled by ESPHome itself.

**Comment by DomiStyle** [comment]
Sure thing! Will take a look after v2 is released.

Is there an API documentation for the Python interface like [there is for the C++ part](https://esphome.io/api/namespaces.html)? Is it possible to add all the sensor/switches/selects into one `climate` block or do I have to resort to individual `sensor`, `select` and `switch` blocks like I'm doing now?

I wrote this with https://github.com/geoffdavis/esphome-mitsubishiheatpump as reference, which has now also moved to `external_components`. They don't use any components except climate though.

**Comment by jesserockz** [comment]
It is possible to include other types inside the climate yaml, and then you can check if the user specified that and ignore those parts in C++

**Comment by DomiStyle** [comment]
Sounds good, do you know an existing component I can use as reference which does that?

**Comment by jesserockz** [comment]
Not off the top of my head.
But basically the same way any other component has sub-components. Perhaps DHT11 is one of the simplest...

**Comment by nrehn** [comment]
+1

**Comment by jesserockz** [comment]
Here you go @DomiStyle #17 :stuck_out_tongue_closed_eyes:

**Comment by DomiStyle** [comment]
Closed via https://github.com/DomiStyle/esphome-panasonic-ac/pull/17

Thanks @jesserockz
