### ISSUE TITLE
Updates online

### ISSUE THREAD

**Issue by sygys** [DomiStyle/esphome-panasonic-ac#18]
I looked at the code of the example.yaml and came across a new line:

```
external_components:
  source: github://DomiStyle/esphome-panasonic-ac@dev-cztacg1
  components: [panasonic_ac]
```

Does this mean it will automatically download the latest files from github instead of needing to download the files and put them in the esphome directory?

If this is true then updating the module in the future is as easy as pressing the install button when things get updated?

**Comment by DomiStyle** [comment]
Yes, the new component will auto update when compiling. Also all sensors are now exposed automatically.

**Comment by sygys** [comment]
I changed the code of my yaml file to:

![image](https://user-images.githubusercontent.com/73538763/129473887-e1ac6940-8001-45c3-9d80-72312a46ede3.png)

But as you can see i get an error. I cannot install the new component while this error presists. What am i missing?

**Comment by sygys** [comment]
if i remove the space in front of the "type: wlan" line i get the error on that line saying "platform not found: climate.Panasonic_ac"

**Comment by sygys** [comment]
Never mind old version of ESPhome....
