### ISSUE TITLE
The current temperature does not work

### ISSUE THREAD

**Issue by galaxes** [DomiStyle/esphome-panasonic-ac#19]
Help, what's wrong ? the current temperature does not work. what needs to be corrected?
![image](https://user-images.githubusercontent.com/16896201/129792086-1d751450-cb4d-49c3-85ef-6a6cda52d3ec.png)

**Comment by DomiStyle** [comment]
Does your AC support reporting the current inside/outside temperature? If so, do you know what the current temperature should be?

**Comment by galaxes** [comment]
I do not know how to check it.
