### ISSUE TITLE
Usage with something else then ESPHome

### ISSUE THREAD

**Issue by Maikel-K** [DomiStyle/esphome-panasonic-ac#3]
Hello,

Im looking into buying a split-unit aircon and like the Etherea looks.
Is it possible to use your code with Domoticz too?

Is the ESP configured to be a Standalone unit which can connect to a MQTT broker for example and can be controlled by any other software sending and pulling data to the MQTT broker?

**Comment by DomiStyle** [comment]
Home Assistant currently directly uses the ESPHome API but all the AC data is exposed as switched and sensors so you can use any method ESPHome supports to control the AC. Including MQTT and HTTP.

I don't have much experience with Domoticz but ESPHome is really flexible.

You can take a look at the example config [here](https://github.com/DomiStyle/esphome-panasonic-ac/blob/master/ac.yaml).

The MQTT documentation is here: https://esphome.io/components/mqtt.html?highlight=mqtt
