### ISSUE TITLE
Where is the WLAN interface on TZ42WKEW indoor AC unit?

### ISSUE THREAD

**Issue by foxy82** [DomiStyle/esphome-panasonic-ac#36]
Hi,

I've got this indoor unit: https://www.youtube.com/watch?v=pGmcqq4a7xs&t=144s
It came with a manual for the DNSK-P11 wifi module and it works with the comfort cloud.

I've managed to connect to the CN-CNT connector and that works great and is easily accessible. 

However I'm looking at how easy it would be to replace the DNSK-P11 however watching the video there doesn't look to be a module as pictured on the instructions. Does anyone know where the module would be in this unit?

Thanks.

**Comment by DomiStyle** [comment]
You could download the service manual from the Panasonic page for your unit and locate the CN-WLAN connector on the board.
