### ISSUE TITLE
Power calculation

### ISSUE THREAD

**Issue by sunsetdk** [DomiStyle/esphome-panasonic-ac#46]
Hi 

is the power calculation correct?

_(uint16_t)(byte_28 + (multiplier * 255)) - offset;_

Is this not ment to be _(uint16_t)(byte_28 + (multiplier * 256)) - offset;_

I know in the grand scheme it doesn't matter :)

But i assume it's 2 bytes for the power, and then one for the offset?

Why would a offset be neeeded? Where did you get the calculations for the power?

**Comment by DomiStyle** [comment]
The power calculation was implemented by @blacklizard  in https://github.com/DomiStyle/esphome-panasonic-ac/issues/9.
I didn't really do anything with it since I don't need it.
