### ISSUE TITLE
many errors

### ISSUE THREAD

**Issue by torrbyll** [DomiStyle/esphome-panasonic-ac#67]
hi 

when i tried to install to my nodemcu (ESP32) i get many errors. 
what can  i have missed?

//Tobias
[logs_ac_upload.txt](https://github.com/DomiStyle/esphome-panasonic-ac/files/9226060/logs_ac_upload.txt)

**Comment by DomiStyle** [comment]
Please update your ESPHome version.

**Comment by torrbyll** [comment]
Tanks nog it works
