### ISSUE TITLE
 auto vertical swing error

### ISSUE THREAD

**Issue by marcolega** [DomiStyle/esphome-panasonic-ac#79]
Hi my panasonic Etherea split (model CS-Z25XKEW) have two different options for automatic vertical swing:
AUTO swing, but flap go fixed in upper position when target temperature is achieved:
![SWING_AUTO](https://user-images.githubusercontent.com/97765943/207609812-c8734183-c8b9-4c96-ad90-554e395ed57f.jpg)

Standard auto swing:
![SWING_OSCILLATION](https://user-images.githubusercontent.com/97765943/207609839-24b238fe-0bde-4eb6-8f59-e0e6eded5220.jpg)

Standard auto swing mode option seem to be not implemented and when I put my split in that mode by remote I have the log:
[14:13:54][W][panasonic_ac.cz_tacg1:374]: Received unknown vertical swing mode
[14:13:54][E][select:018]: 'Studio AC Vertical Swing Mode': invalid state for publish_state(): Unknown

Is it possible to implement both vertical swing mode option?

**Comment by DomiStyle** [comment]
I believe this was implemented very recently in https://github.com/DomiStyle/esphome-panasonic-ac/pull/77.

Can you reflash your ESP with the latest version?

**Comment by marcolega** [comment]
Probabily not. Can you tell how can discover the installed version?

**Comment by DomiStyle** [comment]
It's printed when the ESP is starting but there was no version bump yet for this feature.

ESPHome should automatically pull it when you rebuild the image. If unsure clear the cache first.

**Comment by marcolega** [comment]
Yes I can reflash sorry.
